import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import StoreProvider from "@/providers/StoreProvider";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="flex min-h-screen w-full ">
            <main className="flex-1">{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}

// lofi, cyberpunk, dracula, winter, caramellatte, pastel, cupcake ,nord, dim, business
